[WIP] Make the "gray" state clearer
duckduckgo/privacy-dashboard pull request #164
Opened 2024-07-17 15:30 UTC by mgurgel

**Reviewer:** @shakyShane 

Asana task: https://app.asana.com/0/1206594217596623/1207737672183274/f

## Description:

Make changes to the logic and copy of the privacy dashboard's "gray" state to make it clearer.

## Steps to test this PR:

1. TBC

2024-07-23 15:07 UTC, mgurgel commented on integration-tests/DashboardPage.js
> +        if (this.shouldScreenshotTrackersScreen(state)) {
The “new green” state omits the Tracker Companies link and screen. This was the solution I found to selectively screenshot only states that show that screen, but taking suggestions...

2024-07-23 15:09 UTC, mgurgel commented on integration-tests/macos.spec-int.js
> +test('allowed first party requests', async ({ page }) => {
I added a test case for the the new state, just for added confidence beyond the screenshots.

2024-07-23 15:11 UTC, mgurgel commented on shared/js/ui/templates/key-insights.js
>          if (model.tab.requestDetails.blocked.requestCount === 0) {
Gonna leave the refactor of this bit for the near future if that’s ok

2024-07-23 20:07 UTC, shakyShane commented on integration-tests/DashboardPage.js
> +        if (this.shouldScreenshotTrackersScreen(state)) {
I would focus the language around what the user would experience, like 'is the link there?'

2024-07-23 20:10 UTC, shakyShane requested changes
Excellent work - just the test to tweak.

2024-07-23 20:10 UTC, shakyShane commented on integration-tests/DashboardPage.js
> +
```suggestion
    /**
     * Whether to screenshot the company trackers screen, as some states omit that screen
     */
    async shouldScreenshotTrackersScreen() {
        let count = await this.trackerCompaniesLink().count()
        return count === 1
    }

```

2024-07-23 20:10 UTC, shakyShane commented on integration-tests/DashboardPage.js
> +        if (this.shouldScreenshotTrackersScreen(state)) {
I would just look if the link exists first:

```suggestion
        if (await this.shouldScreenshotTrackersScreen()) {
```

2024-07-23 20:13 UTC, shakyShane commented on shared/js/browser/utils/request-details.test.mjs
> +    })
Thanks for adding this!

2024-07-25 12:20 UTC, mgurgel commented on integration-tests/DashboardPage.js
> +
Changed. Thanks!

2024-07-25 15:44 UTC, shakyShane approved these changes

2024-07-31 10:15 UTC, merged